GET http://localhost:3000/test HTTP/1.1
Content-Type: application/json
Authorization: Barear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMzE3OTkzMSwiZXhwIjoxNzMzMTgzNTMxfQ.03lNJhXi7BfUibeg_tfJcqSovRDG4NuJTuO7H07HMsg