version: '3.8'

services:
  # Node.js service
  app:
    build: .
    container_name: node-app
    environment:
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_USER=bari
      - DB_PASSWORD=root
      - DB_NAME=butterfly
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - backend

  # MySQL service
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: butterfly
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
